apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

bases:
  - ../../base

# CI updates this image tag on every push to dev branch
images:
  - name: agent-mgmt-app
    newName: <YOUR_AWS_ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/agent-mgmt-app
    newTag: dev-latest

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: APP_ENV
          value: development
    target:
      kind: Deployment
      name: agent-mgmt-app
