apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

bases:
  - ../../base

# CI updates this image tag on every push to master branch
images:
  - name: agent-mgmt-app
    newName: 0740-3822-0305.dkr.ecr.eu-north-1.amazonaws.com/agent-mgmt-app
    newTag: prod-latest

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: APP_ENV
          value: production
    target:
      kind: Deployment
      name: agent-mgmt-app
